PRODUCTS = [
{'name': 'Sour cream', 'price': 2.5, 'shop': 'Producty', 'vendor': 'Slabkin'},
{'name': 'Cheese', 'price': 2.5, 'shop': 'Producty', 'vendor': 'Baba Anya'},
{'name': 'Cheese', 'price': 1.6, 'shop': '5ka', 'vendor': 'Slabkin'},
{'name': 'Kefir', 'price': 1.5, 'shop': 'AsiaOpt', 'vendor': 'G&M'},
{'name': 'Sour cream', 'price': 1.9, 'shop': 'Silpo', 'vendor': 'Lidskoe'},
{'name': 'Kefir', 'price': 1.6, 'shop': 'Producty', 'vendor': 'G&M'},
{'name': 'Cheese', 'price': 1.7, 'shop': 'AsiaOpt', 'vendor': 'G&M'},
{'name': 'Milk', 'price': 2.3, 'shop': 'AsiaOpt', 'vendor': 'Lidskoe'},
{'name': 'Kefir', 'price': 1.5, 'shop': '5ka', 'vendor': 'Slabkin'},
{'name': 'Kefir', 'price': 1.7, 'shop': 'Producty', 'vendor': 'Slabkin'},
{'name': 'Milk', 'price': 2.2, 'shop': '5ka', 'vendor': 'Lidskoe'},
{'name': 'Milk', 'price': 1.9, 'shop': 'Producty', 'vendor': 'Baba Anya'},
{'name': 'Cream', 'price': 2.5, 'shop': 'Producty', 'vendor': 'G&M'},
{'name': 'Cream', 'price': 2.2, 'shop': 'Silpo', 'vendor': 'G&M'},
{'name': 'Sour cream', 'price': 1.8, 'shop': 'AsiaOpt', 'vendor': 'G&M'},
{'name': 'Cheese', 'price': 2.3, 'shop': 'Silpo', 'vendor': 'Baba Anya'},
{'name': 'Cheese', 'price': 2.0, 'shop': '5ka', 'vendor': 'G&M'},
{'name': 'Cream', 'price': 1.9, 'shop': 'Producty', 'vendor': 'Lidskoe'},
{'name': 'Sour cream', 'price': 2.2, 'shop': '5ka', 'vendor': 'Lidskoe'},
{'name': 'Cheese', 'price': 2.5, 'shop': 'Producty', 'vendor': 'G&M'},
{'name': 'Kefir', 'price': 2.0, 'shop': 'Silpo', 'vendor': 'Baba Anya'},
{'name': 'Sour cream', 'price': 2.4, 'shop': '5ka', 'vendor': 'Slabkin'},
{'name': 'Kefir', 'price': 1.7, 'shop': 'Silpo', 'vendor': 'G&M'},
{'name': 'Sour cream', 'price': 1.7, 'shop': '5ka', 'vendor': 'Baba Anya'},
{'name': 'Cheese', 'price': 1.9, 'shop': 'Producty', 'vendor': 'Slabkin'},
{'name': 'Sour cream', 'price': 1.6, 'shop': 'Silpo', 'vendor': 'Baba Anya'},
{'name': 'Milk', 'price': 2.3, 'shop': 'Silpo', 'vendor': 'Baba Anya'},
{'name': 'Cream', 'price': 2.4, 'shop': 'Silpo', 'vendor': 'Slabkin'},
{'name': 'Cream', 'price': 2.3, 'shop': 'AsiaOpt', 'vendor': 'Slabkin'},
{'name': 'Kefir', 'price': 1.7, 'shop': 'AsiaOpt', 'vendor': 'Slabkin'},
{'name': 'Kefir', 'price': 2.5, 'shop': 'Producty', 'vendor': 'Baba Anya'},
{'name': 'Cream', 'price': 1.7, 'shop': 'Producty', 'vendor': 'Baba Anya'},
{'name': 'Milk', 'price': 1.7, 'shop': '5ka', 'vendor': 'Baba Anya'},
{'name': 'Cream', 'price': 1.9, 'shop': '5ka', 'vendor': 'G&M'},
{'name': 'Cheese', 'price': 2.5, 'shop': 'Silpo', 'vendor': 'G&M'},
{'name': 'Kefir', 'price': 1.7, 'shop': 'Silpo', 'vendor': 'Slabkin'},
{'name': 'Cream', 'price': 2.0, 'shop': 'Producty', 'vendor': 'Slabkin'},
{'name': 'Kefir', 'price': 2.4, 'shop': '5ka', 'vendor': 'G&M'},
{'name': 'Milk', 'price': 2.0, 'shop': 'Producty', 'vendor': 'G&M'},
{'name': 'Sour cream', 'price': 2.1, 'shop': 'AsiaOpt', 'vendor': 'Baba Anya'},
{'name': 'Kefir', 'price': 1.8, 'shop': 'Silpo', 'vendor': 'Lidskoe'},
{'name': 'Cheese', 'price': 2.3, 'shop': 'Producty', 'vendor': 'Lidskoe'},
{'name': 'Milk', 'price': 1.6, 'shop': 'Silpo', 'vendor': 'Lidskoe'},
{'name': 'Milk', 'price': 2.3, 'shop': 'Silpo', 'vendor': 'G&M'},
{'name': 'Cream', 'price': 1.8, 'shop': 'Silpo', 'vendor': 'Baba Anya'},
{'name': 'Milk', 'price': 1.7, 'shop': 'Producty', 'vendor': 'Slabkin'},
{'name': 'Cream', 'price': 2.4, 'shop': '5ka', 'vendor': 'Baba Anya'},
{'name': 'Sour cream', 'price': 1.7, 'shop': 'Producty', 'vendor': 'Lidskoe'},
{'name': 'Cheese', 'price': 2.2, 'shop': 'AsiaOpt', 'vendor': 'Baba Anya'},
{'name': 'Milk', 'price': 2.1, 'shop': 'Silpo', 'vendor': 'Slabkin'},
{'name': 'Milk', 'price': 1.9, 'shop': 'AsiaOpt', 'vendor': 'Baba Anya'},
{'name': 'Cheese', 'price': 2.4, 'shop': '5ka', 'vendor': 'Lidskoe'},
{'name': 'Kefir', 'price': 1.8, 'shop': 'Producty', 'vendor': 'Lidskoe'},
{'name': 'Milk', 'price': 1.5, 'shop': '5ka', 'vendor': 'G&M'},
{'name': 'Kefir', 'price': 2.4, 'shop': 'AsiaOpt', 'vendor': 'Baba Anya'},
{'name': 'Cheese', 'price': 2.4, 'shop': 'AsiaOpt', 'vendor': 'Lidskoe'},
{'name': 'Sour cream', 'price': 1.5, 'shop': 'Silpo', 'vendor': 'Slabkin'},
{'name': 'Cream', 'price': 2.5, 'shop': 'AsiaOpt', 'vendor': 'Lidskoe'},
{'name': 'Kefir', 'price': 2.3, 'shop': '5ka', 'vendor': 'Lidskoe'},
{'name': 'Cream', 'price': 1.7, 'shop': 'AsiaOpt', 'vendor': 'G&M'},
{'name': 'Cheese', 'price': 1.8, 'shop': 'Silpo', 'vendor': 'Slabkin'}
]
tab =input('Введите товар:')
tab1 =list(filter(lambda x: x['name']==tab,PRODUCTS ))
min_price= min(tab1 , key=lambda p: p['price'])
def handlr(product):
    return f'{product["name"]} можно купить в { product ["shop"]} за {product["price"]} '
print(handlr(min_price))
